// Autogenerated file by PacpusUtilities.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __LIDARVIEWERPLUGIN_H__
#define __LIDARVIEWERPLUGIN_H__

#include <QObject>
#include <qplugin.h>

#include <Pacpus/kernel/PacpusPluginInterface.h>

/// Auto-generated plugin class
class LidarViewerPlugin
    : public QObject
    , public PacpusPluginInterface
{
    Q_OBJECT
    //Qt5 Plugins Macro
    Q_PLUGIN_METADATA(IID "pacpus.LidarViewerPlugin" FILE "LidarViewerPlugin.json")
    Q_INTERFACES(PacpusPluginInterface)

public:
    LidarViewerPlugin();
    ~LidarViewerPlugin();

protected:
    QString name();
};

#endif // __LIDARVIEWERPLUGIN_H__
