// Autogenerated file by PacpusUtilities.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#ifndef __LIDARVIEWER_CONFIG_H__
#define __LIDARVIEWER_CONFIG_H__

// Export macro for use DLL for Windows only
#ifdef WIN32
   #ifdef LIDARVIEWER_EXPORTS
//      make DLL
       #define LIDARVIEWER_API __declspec(dllexport)
   #else
//      use DLL
       #define LIDARVIEWER_API __declspec(dllimport)
   #endif
#else
//      On other platforms, simply ignore this
   #define LIDARVIEWER_API
#endif

#endif // __LIDARVIEWER_CONFIG_H__
