// Autogenerated file by PacpusUtilities.cmake
// DO NOT EDIT!!! ALL CHANGES WOULD BE REMOVED BY THE NEXT CALL OF CMAKE

#include "LidarViewerPlugin.h"

LidarViewerPlugin::LidarViewerPlugin()
{
}

LidarViewerPlugin::~LidarViewerPlugin()
{
}

QString LidarViewerPlugin::name()
{
    return "LidarViewerPlugin";
}

//Qt4 Plugin Macro desactivated
//Q_EXPORT_PLUGIN2(LidarViewerPlugin, LidarViewerPlugin)
